# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BrainStorm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CircleMenu'
  pod 'Macaw'


  target 'BrainStormTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
